apiVersion: v1
kind: Service
metadata:
  name: mediaserver
spec:
  type: ClusterIP
  selector:
    app: mediaserver
  ports:
    - name: webrtc
      port: 8889
      targetPort: 8889
    - name: rtsp
      port: 8554
      targetPort: 8554
    - name: rtmp
      port: 1935
      targetPort: 1935
    - name: rtp
      port: 8000
      targetPort: 8000
    - name: rtcp
      port: 8001
      targetPort: 8001
    - name: upd
      port: 8189
      targetPort: 8189