replicaCount: 1

app:
    name: streamgw
    component: backend
    manager: helm

deployments:
  name: streamgw
  containerPort: 3000
  imagePullPolicy: Always

ingress:
  name: http
  protocol: HTTP
  port: 83
  extension: svc.cluster.local

image:
  repository: pombnk/streamgw
  pullPolicy: IfNotPresent
  tag: latest

#migration:
#  repository: pombnk/ordermigrations
#  pullPolicy: IfNotPresent
#  tag: latest


