apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  type: ClusterIP
  selector:
    app: jaeger
  ports:
    - name: collector
      port: 4318
      targetPort: 4318
    - name: ui
      port: 16686
      targetPort: 16686
